In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Importing the dataset
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%cd /content/drive/MyDrive/Y4/
ds = pd.read_csv('Dataset.csv')
ds

/content/drive/MyDrive/Y4


P.H  Soil EC  phosporus  Pottasium  Urea  T.S.P  M.O.P      Tree
0    4.6    0.300        9.5       74.8    96     20     46      Rice
1    4.3    0.150       14.6       89.0    96      0     23      Rice
2    3.8    0.100        5.9       56.4    96     20     36      Rice
3    4.0    0.150        5.8       70.6    96     20     46      Rice
4    5.1    0.240        6.0       64.9    96     20     46      Rice
..   ...      ...        ...        ...   ...    ...    ...       ...
294  7.4    0.020        9.5       57.5    30     14      0  Turmeric
295  7.5    0.030       10.0       52.8    30      5     20  Turmeric
296  7.3    0.048       11.6       53.3    30      0     14  Turmeric
297  7.0    0.033        8.9       51.6    30     14     20  Turmeric
298  7.5    0.030       10.5       56.0    30      5      0  Turmeric

[299 rows x 8 columns]

In [4]:
X = ds.iloc[:, 0:7].values
Y = ds.iloc[:, -1].values
print(X[3])
print(Y[3])

[ 4.    0.15  5.8  70.6  96.   20.   46.  ]
Rice


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [6]:
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

[[7.10e+00 3.15e-01 6.60e+00 ... 2.50e+01 6.00e+00 1.20e+01]
 [7.00e+00 2.12e-01 6.40e+00 ... 2.50e+01 6.00e+00 0.00e+00]
 [6.10e+00 3.10e-02 5.10e+00 ... 4.50e+01 1.20e+01 1.40e+01]
 ...
 [6.90e+00 8.70e-02 5.70e+00 ... 4.50e+01 0.00e+00 0.00e+00]
 [5.60e+00 6.50e-02 2.00e+01 ... 1.60e+02 0.00e+00 4.40e+01]
 [7.00e+00 2.09e-01 5.70e+00 ... 2.50e+01 1.00e+01 0.00e+00]]
['Tomato' 'Tomato' 'Cinnamon' 'Turmeric' 'Turmeric' 'Turmeric' 'Turmeric'
 'Cinnamon' 'Rice' 'Rice' 'Tomato' 'Turmeric' 'Turmeric' 'Rice' 'Tomato'
 'Turmeric' 'Rice' 'Cinnamon' 'Tomato' 'Tomato' 'Cinnamon' 'Tomato'
 'Turmeric' 'Turmeric' 'Turmeric' 'Cinnamon' 'Turmeric' 'Turmeric'
 'Turmeric' 'Turmeric' 'Turmeric' 'Rice' 'Turmeric' 'Tomato' 'Tomato'
 'Tomato' 'Cinnamon' 'Cinnamon' 'Tomato' 'Rice' 'Turmeric' 'Turmeric'
 'Tomato' 'Tomato' 'Cinnamon' 'Turmeric' 'Turmeric' 'Turmeric' 'Turmeric'
 'Turmeric' 'Tomato' 'Tomato' 'Rice' 'Cinnamon' 'Turmeric' 'Cinnamon'
 'Tomato' 'Turmeric' 'Cinnamon' 'Rice' 'Rice' 'Tomato' 'Rice' 

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
print(X_train[3])
print(X_test[3])

[ 0.57747083 -0.63296111  0.07337027 -0.52197672 -0.48308742 -0.28022772
  0.81568097]
[ 1.04571689e+00 -5.52946457e-01 -3.08278450e-04 -2.86520724e-01
 -4.83087417e-01  1.03299629e+00 -9.11813506e-01]


In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, Y_train)

SVC(kernel='linear', random_state=0)

In [10]:
print(classifier.predict(sc.transform([[4.5,0.3,9.5,74.8,96,20,46]])))

['Rice']


In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[['Turmeric' 'Turmeric']
 ['Tomato' 'Tomato']
 ['Rice' 'Rice']
 ['Turmeric' 'Turmeric']
 ['Turmeric' 'Turmeric']
 ['Tomato' 'Tomato']
 ['Turmeric' 'Turmeric']
 ['Turmeric' 'Turmeric']
 ['Cinnamon' 'Cinnamon']
 ['Cinnamon' 'Cinnamon']
 ['Turmeric' 'Turmeric']
 ['Rice' 'Rice']
 ['Tomato' 'Tomato']
 ['Turmeric' 'Turmeric']
 ['Rice' 'Rice']
 ['Cinnamon' 'Cinnamon']
 ['Turmeric' 'Turmeric']
 ['Cinnamon' 'Cinnamon']
 ['Turmeric' 'Turmeric']
 ['Turmeric' 'Turmeric']
 ['Tomato' 'Tomato']
 ['Cinnamon' 'Cinnamon']
 ['Cinnamon' 'Cinnamon']
 ['Tomato' 'Tomato']
 ['Turmeric' 'Turmeric']
 ['Cinnamon' 'Cinnamon']
 ['Tomato' 'Tomato']
 ['Turmeric' 'Turmeric']
 ['Turmeric' 'Turmeric']
 ['Turmeric' 'Turmeric']
 ['Cinnamon' 'Cinnamon']
 ['Cinnamon' 'Cinnamon']
 ['Rice' 'Rice']
 ['Cinnamon' 'Cinnamon']
 ['Turmeric' 'Turmeric']
 ['Tomato' 'Tomato']
 ['Tomato' 'Tomato']
 ['Tomato' 'Tomato']
 ['Turmeric' 'Turmeric']
 ['Rice' 'Rice']
 ['Turmeric' 'Turmeric']
 ['Cinnamon' 'Cinnamon']
 ['Cinnamon' 'Cinnamon']
 